package constants

//go:generate stringer -type=ClientState
type ClientState int

const (
	ClientStateHandshaking ClientState = iota
	ClientStateStatus
	ClientStateLogin
	ClientStateConfiguration
	ClientStatePlay
	ClientStateTransfer
)

// Conversion from int to ClientState with checking
func ClientStateFromInt(i int) (ClientState, bool) {
	if i < 0 || i >= len(_ClientState_index) { // _ClientState_index is generated by stringer
		return 0, false
	}
	return ClientState(i), true
}
