// Code generated by "stringer -type=ClientState"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClientStateHandshaking-0]
	_ = x[ClientStateStatus-1]
	_ = x[ClientStateLogin-2]
	_ = x[ClientStateConfiguration-3]
	_ = x[ClientStatePlay-4]
	_ = x[ClientStateTransfer-5]
}

const _ClientState_name = "ClientStateHandshakingClientStateStatusClientStateLoginClientStateConfigurationClientStatePlayClientStateTransfer"

var _ClientState_index = [...]uint8{0, 22, 39, 55, 79, 94, 113}

func (i ClientState) String() string {
	if i < 0 || i >= ClientState(len(_ClientState_index)-1) {
		return "ClientState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClientState_name[_ClientState_index[i]:_ClientState_index[i+1]]
}
